
# SEO settings
title: "Cinfwat"
title2: "Dogak" # default: ""
description: "Ramblings of a Data Scientist (Toddler)"
keywords: "Data Science, Machine Learning, python, blog, D3.js, Node.js, Bookeh, R, Matlab, Data Visualistion"
url: http://cinfwatd.github.io # site url
baseurl: null # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/cinfwatd/cinfwatd.github.io
disqus_shortname: "heiswayi"
twitter_username: "CinfwatD"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Cinfwat Dogak"
  job      : "MSc Data Science Student at the University of Southampton, UK"
  bio      : "Bio"
  thumb    : /images/author.jpg
  email    : czp@gmail.com
  url      : http://cinfwatd.github.io
  github   : http://github.com/cinfwatd
  twitter  : http://twitter.com/cinfwatd
  facebook : https://www.facebook.com/cinfwatd
  linkedin : http://linkedin.com/in/

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@CinfwatD"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
